name = "swap-example-mcp"
main = "src/index.ts"

compatibility_date = "2025-03-10"
compatibility_flags = ["nodejs_compat"]

durable_objects.bindings = [
  { name = "MCP_OBJECT", class_name = "MyMCP" }
]

migrations = [
  { tag = "v1", "new_sqlite_classes" = ["MyMCP"] }
]

[observability.logs]
enabled = true

[triggers]
crons = [ "59 * * * *" ]
