name = "swap-example-mcp"
main = "src/index.ts"

compatibility_date = "2025-03-10"
compatibility_flags = ["nodejs_compat"]

durable_objects.bindings = [
  { name = "MCP_OBJECT", class_name = "MyMCP" }
]

migrations = [
  { tag = "v1", "new_sqlite_classes" = ["MyMCP"] }
]

[observability.logs]
enabled = true

[triggers]
crons = [ "*/5 * * * *" ]

# SERVER_URL should match with the final MCP worker url (dev or custom domain)
[vars]
SERVER_URL = "https://swap-example-mcp.nestordetoke.workers.dev/mcp" # Keep the last /mcp for the registration process
